---
- name: Add SSH key from vault to remote hosts
  hosts: oraclelinux
  become: yes

  vars:
    ansible_user: nagios
    ansible_ssh_pass: "admin"
    ansible_become: yes
    ansible_become_method: sudo
    ansible_become_pass: "admin"
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    nagios_user: nagios
    nagios_group: nagios

